version: '3.3'

services:
  flask-backend:
    image: flask-backend
    ports:
      - "8080:8080"
    environment:
      - BACKEND_PORT=8080
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=company
    volumes:
          - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

