INSERT INTO employees (name, age, role) VALUES
('Alice Johnson', 28, 'Software Engineer'),
('Bob Smith', 34, 'Data Scientist'),
('Carol Davis', 22, 'Product Manager'),
('David Brown', 40, 'Project Lead'),
('Emma Wilson', 31, 'UX Designer'),
('Frankie Adams', 29, 'DevOps Engineer'),
('Grace Lee', 37, 'Marketing Specialist'),
('Henry Martinez', 45, 'Systems Administrator'),
('Ivy Clark', 26, 'Sales Representative'),
('Jack Green', 33, 'Business Analyst'),
('Karen Harris', 30, 'HR Manager'),
('Louis Thompson', 25, 'Junior Developer'),
('Megan Hall', 32, 'Graphic Designer'),
('Nathan King', 38, 'Network Engineer'),
('Olivia Scott', 27, 'Content Strategist'),
('Paul Taylor', 42, 'Technical Writer'),
('Quinn White', 31, 'Customer Support'),
('Rachel Young', 24, 'Marketing Coordinator'),
('Steve Roberts', 46, 'Finance Manager'),
('Tina Nelson', 28, 'Administrative Assistant'),
('Ulysses Walker', 35, 'Operations Manager'),
('Vera Allen', 29, 'Product Designer'),
('Will Brown', 41, 'Senior Software Engineer'),
('Xena Harris', 33, 'Data Analyst'),
('Yvonne Carter', 27, 'Quality Assurance'),
('Zachary Lewis', 39, 'IT Specialist'),
('Aiden Adams', 24, 'Junior Data Scientist'),
('Bella Martinez', 30, 'Digital Marketing Specialist'),
('Carter Evans', 34, 'Web Developer'),
('Diana King', 29, 'SEO Specialist'),
('Ethan Wilson', 37, 'Business Development'),
('Fiona Scott', 32, 'Operations Analyst'),
('George Robinson', 40, 'Security Analyst'),
('Hannah Clark', 26, 'Content Writer'),
('Isaac Thomas', 28, 'Customer Success Manager'),
('Jasmine Anderson', 35, 'Project Coordinator'),
('Kevin Lee', 31, 'Database Administrator'),
('Laura Scott', 26, 'Social Media Manager'),
('Mark Lewis', 43, 'Systems Architect'),
('Nora Hall', 29, 'Software Tester'),
('Oscar Adams', 34, 'DevOps Specialist'),
('Paige Thompson', 31, 'E-commerce Manager'),
('Quincy Rogers', 27, 'Business Consultant'),
('Rebecca Young', 36, 'Product Owner'),
('Samuel Walker', 30, 'IT Support Specialist'),
('Taylor Green', 25, 'Junior Project Manager'),
('Ursula Baker', 32, 'Talent Acquisition Specialist'),
('Victor Hill', 38, 'Cloud Engineer'),
('Wendy Allen', 40, 'Compliance Officer'),
('Xander Lewis', 29, 'User Experience Researcher'),
('Yara Rodriguez', 31, 'Sales Manager'),
('Zane Johnson', 28, 'Financial Analyst'),
('Anna Martinez', 27, 'Software Engineer'),
('Ben Lewis', 33, 'Data Scientist'),
('Clara White', 25, 'Product Manager'),
('Daniel Harris', 41, 'Project Lead'),
('Ella Johnson', 29, 'UX Designer'),
('Finn Clark', 31, 'DevOps Engineer'),
('Grace Baker', 38, 'Marketing Specialist'),
('Harry Young', 42, 'Systems Administrator'),
('Ivy Adams', 26, 'Sales Representative'),
('Jack King', 34, 'Business Analyst'),
('Kara Scott', 30, 'HR Manager'),
('Leo Thompson', 27, 'Junior Developer'),
('Mia Roberts', 32, 'Graphic Designer'),
('Noah Walker', 36, 'Network Engineer'),
('Olivia Davis', 25, 'Content Strategist'),
('Paul White', 44, 'Technical Writer'),
('Quinn Lewis', 29, 'Customer Support'),
('Riley Allen', 24, 'Marketing Coordinator'),
('Samantha Martin', 39, 'Finance Manager'),
('Thomas Walker', 28, 'Administrative Assistant'),
('Uma Evans', 35, 'Operations Manager'),
('Victor Nelson', 30, 'Product Designer'),
('Wendy Harris', 42, 'Senior Software Engineer'),
('Xander Adams', 33, 'Data Analyst'),
('Yasmine Brown', 26, 'Quality Assurance'),
('Zachary Smith', 40, 'IT Specialist'),
('Ava Johnson', 24, 'Junior Data Scientist'),
('Brian Martinez', 31, 'Digital Marketing Specialist'),
('Chloe Evans', 34, 'Web Developer'),
('Derek King', 29, 'SEO Specialist'),
('Ella Green', 37, 'Business Development'),
('Felix Carter', 32, 'Operations Analyst'),
('Gina Hall', 41, 'Security Analyst'),
('Hannah Adams', 28, 'Content Writer'),
('Ian Robinson', 35, 'Customer Success Manager'),
('Julia Clark', 30, 'Project Coordinator'),
('Kevin Scott', 31, 'Database Administrator'),
('Laura Brown', 26, 'Social Media Manager'),
('Michael Young', 44, 'Systems Architect'),
('Nina Thompson', 29, 'Software Tester'),
('Oscar Nelson', 34, 'DevOps Specialist'),
('Pamela Wilson', 31, 'E-commerce Manager'),
('Quincy Green', 27, 'Business Consultant'),
('Rachel Rodriguez', 36, 'Product Owner'),
('Steve Walker', 30, 'IT Support Specialist'),
('Tina Lewis', 25, 'Junior Project Manager'),
('Ursula Martinez', 32, 'Talent Acquisition Specialist'),
('Victor Allen', 38, 'Cloud Engineer'),
('Wendy Adams', 40, 'Compliance Officer'),
('Xena Johnson', 29, 'User Experience Researcher'),
('Yvonne Davis', 31, 'Sales Manager'),
('Zane Clark', 28, 'Financial Analyst');